version: '3'

services:
  hospital_neo4j_etl:
    image: clbo/hospital_neo4j_etl:${TAG:-latest}
    env_file:
      - .env

  chatbot_api:
    image: clbo/chatbot_api:${TAG:-latest}
    env_file:
      - .env
    depends_on:
      - hospital_neo4j_etl
    ports:
      - "8000:8000"

  chatbot_frontend:
    image: clbo/chatbot_frontend:${TAG:-latest}
    env_file:
      - .env
    depends_on:
      - chatbot_api
    ports:
      - "8501:8501"
